//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakta1entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int ID_Deliveryman { get; set; }
        public string NameDeliveryman { get; set; }
        public string SurnameDeliveryman { get; set; }
        public Nullable<int> Rating { get; set; }
        public string PhoneNumber { get; set; }
        public int Order_ID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
