//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prakta1entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRecipient
    {
        public int ID_OrderRecipient { get; set; }
        public int Order_ID { get; set; }
        public string RecipientName { get; set; }
        public string RecipientSurname { get; set; }
        public double WeightReceived { get; set; }
        public int QuantityReceived { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
